---
- name: Print Quick Course workload information
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
  - "Deploying Quick Course on OpenShift"
  - "GUID: {{ guid }}"
  - "Namespace: {{ ocp4_workload_quickcourse_namespace }}"
  - "Content Repository: {{ ocp4_workload_quickcourse_content_git_repo }}"
  - "Content Ref: {{ ocp4_workload_quickcourse_content_git_repo_ref }}"
  - "Deployment Type: {{ ocp4_workload_quickcourse_deployment_type }}"

- name: Check if OCP CLI is available
  ansible.builtin.command: oc version
  register: r_oc_version
  changed_when: false
  failed_when: false

- name: Assert OCP CLI is available
  ansible.builtin.assert:
    that:
    - r_oc_version.rc == 0
    fail_msg: "OpenShift CLI (oc) is not available or not logged in"
    quiet: true
