---
# Implement your workload removal tasks here
# ------------------------------------------

# This playbook is called upon deletion of the environment
# OpenShift resources get deleted automatically
#
# Leave this as the last task in the playbook.
# --------------------------------------------

- name: Prepare Variables
  ansible.builtin.include_tasks: prepare-variables.yaml

- name: Remove Projects (single user)
  when: not _quickcourse_user_data.users is defined
  kubernetes.core.k8s:
    kubeconfig: "{{ _quickcourse_kubeconfig | default(omit) }}"
    state: absent
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ ocp4_workload_quickcourse_namespace }}"
  ignore_errors: true

- name: Remove Projects (multi user)
  when: _quickcourse_user_data.users is defined
  vars:
    _quickcourse_user: "{{ _quickcourse_users_item.key }}"
    _quickcourse_namespace: "{{ ocp4_workload_quickcourse_namespace }}-{{ _quickcourse_user }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ _quickcourse_kubeconfig | default(omit) }}"
    state: absent
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ _quickcourse_namespace }}"
  ignore_errors: true
  loop: >-
    {{ _quickcourse_user_data.users | dict2items }}
  loop_control:
    loop_var: _quickcourse_users_item
    label: "{{ _quickcourse_users_item.key }}"

- name: Remove_workload tasks complete
  when: not silent | bool
  ansible.builtin.debug:
    msg: "Remove Workload tasks completed successfully."
